#!/bin/sh -x
if test ! "x$(which libtoolize)" = "x"; then
  echo "Running libtoolize"
  libtoolize --copy
else
  if test ! "x$(which gintltoolize)" = "x"; then
    echo "Running glibtoolize"
    glibtoolize --copy
  fi
fi
exec autoreconf --install --verbose

